title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
<<<<<<< HEAD
theme: jekyll-theme-hacker
=======
theme: jekyll-theme-architect
=======
title:

theme: jekyll-theme-dinky
>>>>>>> 16508c02f3526edbcefdcf752366629231a7d49a
>>>>>>> 7eda226363c06fc00809b293f6cf55ee66080da9
